### ISSUE TITLE
Unable to install requirements.txt

### ISSUE THREAD

**Issue by lcdbezerra** [uoe-agents/epymarl#35] opened 2022-10-27 18:20 UTC
```
The conflict is caused by:
    The user requested protobuf==3.6.1
    pysc2 3.0.0 depends on protobuf>=2.6
    s2clientprotocol 4.10.1.75800.0 depends on protobuf
    smac 1.0.0 depends on protobuf==3.19.5
```
The SMAC repo requirements were recently updated to include `protobuf==3.19.5`. I think the SMAC version that EPyMARL uses should be specified in `requirements.txt`.

**Comment by lucascamaradb** [comment] 2022-10-28 14:58
I believe I fixed it. The changes to `requirements.txt` were:

```
# protobuf==3.6.1
protobuf
importlib-metadata<5.0
```

Running Python 3.7.13. Python 3.10 is not supported, since `collections.Mapping` is now deprecated.

**Comment by JosephTrevorrow** [comment] 2022-11-08 16:11
I had the same set of issues, did your fix but still can't build the docker file 

> executor failed running [/bin/sh -c apt-get update -y && apt-get install software-properties-common -y &&     add-apt-repository -y multiverse && apt-get update -y && apt-get upgrade -y &&     apt-get install -y apt-utils nano vim man build-essential wget sudo &&     rm -rf /var/lib/apt/lists/*]: exit code: 100

I get this error at the end running Python 3.9

**Comment by papoudakis** [comment] 2022-11-09 10:42
You do not have to install a docker for running EPyMARL. We recommend using a conda environment for installing the requirements.

**Comment by altanturkoglu** [comment] 2023-01-28 19:04
The issue is a version mismatch of `protobuf` between `epymarl` and `SMAC`. Commits updating requirements for SMAC are what broke the installation:
https://github.com/oxwhirl/smac/commit/c22d82c4285bb85b2425e6db0b3e35411166d92f 
https://github.com/oxwhirl/smac/commit/26f4c4e4d1ebeaf42ecc2d0af32fac0774ccc678

A simple fix that also worked for me is to do as @lcdbezerra suggested and remove the specific version number on `protobuf` in `requirements.txt`.

**Comment by LukasSchaefer** [comment] 2024-07-23 11:25
Hi! Sorry for the very late response.

We just published a big update to EPyMARL including lots of new features (including training in non-common-reward games, move to gymnasium from deprecated gym, weights and biases logging) that among others tidies up the dependencies of several environments and moves to the maintained `gymnasium` library in replacement of the deprecated `gym`. This should fix your issues.

I will close the issue for now, but please let us know if there are any outstanding issues!

**Closed by LukasSchaefer** 2024-07-23 11:25 UTC
